### ISSUE TITLE
Docker-compose.yml does not standardize the developers' environments

### ISSUE THREAD

**Issue by ryotaro-tanaka** [ryotaro-tanaka/jobhuntx#12]
Currently, to run the application with this Docker setup, you must upload your local node_modules to the container. In other words, you need to run either npm install or pnpm install locally before starting the Docker container.

**Comment by ryotaro-tanaka** [comment]
* plan A
```yml
  frontend:
    image: node:18
    command: ["pnpm", "install", "&&","pnpm", "run", "dev"]
```

* plan B
creating dockerfile based by node:18
