### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by ryotaro-tanaka** [ryotaro-tanaka/jobhuntx#5]
```yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend-dev
    ports:
      - "3000:3000" # Reactの開発サーバー
    volumes:
      - ./ClientApp:/app/ClientApp # ホットリロード用
    environment:
      - CHOKIDAR_USEPOLLING=true # WSL環境でファイル変更を検知するため

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend-dev
    ports:
      - "5000:5000" # ASP.NET Coreの開発サーバー
    volumes:
      - .:/src # ホットリロード用
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1 # WSL環境でファイル変更を検知するため
```

By using Docker Compose, development and production environments can be easily managed and switched.

In the development environment, you can enable hot reload by combining docker-compose.yml and Dockerfile.dev. In the production environment, you can create a lightweight image using docker-compose.prod.yml and a production-specific Dockerfile

**Comment by ryotaro-tanaka** [comment]
I had created Dockerfiles for production and development, but I want to discontinue those and set up the development environment for React and ASP.NET using Docker Compose.

```yml
version: '3.8'
services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./client-app:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    command: ["dotnet", "watch", "run", "--project", "JobHuntX/JobHuntX.csproj"]
```
